<a href="https://colab.research.google.com/github/juliagermanosilva-pixel/Dados_poluicao_2025_2026/blob/main/Dados_poluicao_global_2025_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/ChiaviniK/dados_polui-o_2526.git

Cloning into 'dados_polui-o_2526'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), 297.43 KiB | 6.61 MiB/s, done.

In [4]:
import pandas as pd
import numpy as np
#método de extração - raw (cru - em português)
#ETL - Extract - Transform - Load
df_dados_raw = pd.read_csv('/content/dados_polui-o_2526/Global_Air_Pollution_Data_2025_2026.csv')
#ver os dados carregados
display(df_dados_raw)

,Date,City,Latitude,Longitude,PM2.5,PM10,NO2,SO2,CO,Ozone,Aerosol_Optical_Depth,AQI_Class
0,2025-11-08 00:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy
1,2025-11-08 01:00:00,"Lahore, Pakistan",31.5497,74.3436,78.2,79.6,90.9,14.4,1413.0,10.0,0.19,Unhealthy
2,2025-11-08 02:00:00,"Lahore, Pakistan",31.5497,74.3436,75.4,76.8,85.0,12.8,1060.0,12.0,0.19,Unhealthy
3,2025-11-08 03:00:00,"Lahore, Pakistan",31.5497,74.3436,72.2,73.6,72.8,11.8,863.0,20.0,0.19,Unhealthy
4,2025-11-08 04:00:00,"Lahore, Pakistan",31.5497,74.3436,69.8,71.2,57.7,11.1,811.0,31.0,0.19,Unhealthy
...,...,...,...,...,...,...,...,...,...,...,...,...
17467,2026-02-06 19:00:00,"Jakarta, Indonesia",-6.2088,106.8456,49.4,49.9,48.6,39.2,3014.0,5.0,0.16,Unhealthy for Sensitive
17468,2026-02-06 20:00:00,"Jakarta, Indonesia",-6.2088,106.8456,59.6,60.5,47.3,41.6,2791.0,1.0,0.15,Unhealthy
17469,2026-02-06 21:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,41.5,42.5,2200.0,1.0,0.16,Unhealthy
17470,2026-02-06 22:00:00,"Jakarta, Indonesia",-6.2088,106.8456,61.5,62.2,36.0,42.0,1672.0,1.0,0.16,Unhealthy
17471,2026-02-06 23:00:00,"Jakarta, Indonesia",-6.2088,106.8456,60.1,60.8,32.2,39.7,1343.0,1.0,0.17,Unhealthy

In [5]:
#analise preliminar dos dados
#analise de estrutura de dados
df_dados_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17472 entries, 0 to 17471
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   17472 non-null  object
 1   City                   17472 non-null  object
 2   Latitude               17472 non-null  float64
 3   Longitude              17472 non-null  float64
 4   PM2.5                  17472 non-null  float64
 5   PM10                   17472 non-null  float64
 6   NO2                    17472 non-null  float64
 7   SO2                    17472 non-null  float64
 8   CO                     17472 non-null  float64
 9   Ozone                  17472 non-null  float64
 10  Aerosol_Optical_Depth  17472 non-null  float64
 11  AQI_Class              17472 non-null  object
dtypes: float64(9), object(3)
memory usage: 1.6+ MB

In [6]:
#resumo estatisticoo
df_dados_raw.describe().T

,count,mean,std,min,25%,50%,75%,max
Latitude,17472.0,23.292375,23.814690,-23.5505,16.305525,30.0818,40.106350,51.5074
Longitude,17472.0,43.056375,68.421659,-74.0060,-11.754175,75.7763,94.520775,116.4074
PM2.5,17472.0,66.060611,65.414505,0.3000,13.175000,45.5000,99.700000,430.3000
PM10,17472.0,69.263124,66.576392,0.4000,14.800000,48.9000,104.300000,434.0000
NO2,17472.0,38.458871,26.977070,0.0000,17.700000,31.8000,53.600000,185.1000
SO2,17472.0,30.292691,41.777128,0.0000,6.100000,14.4000,37.900000,439.3000
CO,17472.0,1264.659741,1484.401277,0.0000,278.000000,713.0000,1627.000000,13039.0000
Ozone,17472.0,54.746337,49.928268,0.0000,16.000000,45.0000,71.000000,288.0000
Aerosol_Optical_Depth,17472.0,0.325342,0.255573,0.0100,0.120000,0.2700,0.470000,2.9800

In [14]:
#vamos criar nossa engenharia de dados
def pipeline(df):
  #vamos criar nosso backup
  df_limpos = df.copy()
  #sempre que você trabalha com BI'sou SQL
  #padroziação dos nomes para uso (fazer tudo ficar em snack case)
  df_limpos.columns = [col.lower().replace(' ','_')
  for col in df_limpos.columns]
  #regra de negocio - traduzir para algo legivel
  condicoes = [
      (df_limpos['pm2.5'] <= 12),
      (df_limpos['pm2.5'] <= 35.5),
      (df_limpos['pm2.5'] <= 55.4),
      (df_limpos['pm2.5'] <= 150.4),
      (df_limpos['pm2.5'] > 150.5)
  ]
  escolha = ['Boa',
             'Moderado',
             'Insalubre para grupos sensiveis',
             'Insalubre',
             'Muito Insalubre/Perigoso'
  ]
  #criar um padrão para os dados
  df_limpos['timestamp'] = pd.to_datetime(df_limpos['date'])
  #agora vamos criar o campo para traduzir os numeros para as escolhas
  df_limpos['status_saude'] = np.select(condicoes, escolha, default='N/A')
  df_limpos['dia'] = df_limpos['timestamp'].dt.day
  df_limpos['Mês'] = df_limpos['timestamp'].dt.month
  df_limpos['Ano'] = df_limpos['timestamp'].dt.year
  df_limpos['Data'] = df_limpos['timestamp'].dt.date
  df_limpos['Hora'] = df_limpos['timestamp'].dt.hour
  return df_limpos

In [15]:
df_poluicao_final = pipeline(df_dados_raw)
df_poluicao_final.head(50)

,date,city,latitude,longitude,pm2.5,pm10,no2,so2,co,ozone,aerosol_optical_depth,aqi_class,timestamp,status_saude,dia,Mês,Ano,Data,Hora
0,2025-11-08 00:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,94.0,16.4,1910.0,11.0,0.19,Unhealthy,2025-11-08 00:00:00,Insalubre,8,11,2025,2025-11-08,0
1,2025-11-08 01:00:00,"Lahore, Pakistan",31.5497,74.3436,78.2,79.6,90.9,14.4,1413.0,10.0,0.19,Unhealthy,2025-11-08 01:00:00,Insalubre,8,11,2025,2025-11-08,1
2,2025-11-08 02:00:00,"Lahore, Pakistan",31.5497,74.3436,75.4,76.8,85.0,12.8,1060.0,12.0,0.19,Unhealthy,2025-11-08 02:00:00,Insalubre,8,11,2025,2025-11-08,2
3,2025-11-08 03:00:00,"Lahore, Pakistan",31.5497,74.3436,72.2,73.6,72.8,11.8,863.0,20.0,0.19,Unhealthy,2025-11-08 03:00:00,Insalubre,8,11,2025,2025-11-08,3
4,2025-11-08 04:00:00,"Lahore, Pakistan",31.5497,74.3436,69.8,71.2,57.7,11.1,811.0,31.0,0.19,Unhealthy,2025-11-08 04:00:00,Insalubre,8,11,2025,2025-11-08,4
5,2025-11-08 05:00:00,"Lahore, Pakistan",31.5497,74.3436,66.8,68.2,45.0,11.1,1088.0,43.0,0.20,Unhealthy,2025-11-08 05:00:00,Insalubre,8,11,2025,2025-11-08,5
6,2025-11-08 06:00:00,"Lahore, Pakistan",31.5497,74.3436,71.2,72.6,51.0,11.4,2069.0,36.0,0.20,Unhealthy,2025-11-08 06:00:00,Insalubre,8,11,2025,2025-11-08,6
7,2025-11-08 07:00:00,"Lahore, Pakistan",31.5497,74.3436,80.3,82.0,58.7,11.9,3380.0,28.0,0.21,Unhealthy,2025-11-08 07:00:00,Insalubre,8,11,2025,2025-11-08,7
8,2025-11-08 08:00:00,"Lahore, Pakistan",31.5497,74.3436,79.6,81.0,59.7,13.0,4085.0,34.0,0.21,Unhealthy,2025-11-08 08:00:00,Insalubre,8,11,2025,2025-11-08,8
9,2025-11-08 09:00:00,"Lahore, Pakistan",31.5497,74.3436,71.9,73.1,47.8,15.5,3616.0,68.0,0.20,Unhealthy,2025-11-08 09:00:00,Insalubre,8,11,2025,2025-11-08,9
10,2025-11-08 10:00:00,"Lahore, Pakistan",31.5497,74.3436,53.7,55.3,29.2,18.7,2540.0,116.0,0.20,Unhealthy for Sensitive,2025-11-08 10:00:00,Insalubre para grupos sensiveis,8,11,2025,2025-11-08,10
11,2025-11-08 11:00:00,"Lahore, Pakistan",31.5497,74.3436,29.3,31.0,14.8,20.4,1624.0,153.0,0.21,Moderate,2025-11-08 11:00:00,Moderado,8,11,2025,2025-11-08,11
12,2025-11-08 12:00:00,"Lahore, Pakistan",31.5497,74.3436,23.3,25.0,7.5,19.3,1071.0,169.0,0.21,Moderate,2025-11-08 12:00:00,Moderado,8,11,2025,2025-11-08,12
13,2025-11-08 13:00:00,"Lahore, Pakistan",31.5497,74.3436,21.9,23.7,4.4,16.6,678.0,172.0,0.21,Moderate,2025-11-08 13:00:00,Moderado,8,11,2025,2025-11-08,13
14,2025-11-08 14:00:00,"Lahore, Pakistan",31.5497,74.3436,21.5,23.3,6.9,14.6,599.0,167.0,0.22,Moderate,2025-11-08 14:00:00,Moderado,8,11,2025,2025-11-08,14
15,2025-11-08 15:00:00,"Lahore, Pakistan",31.5497,74.3436,21.5,23.2,17.2,13.8,995.0,150.0,0.21,Moderate,2025-11-08 15:00:00,Moderado,8,11,2025,2025-11-08,15
16,2025-11-08 16:00:00,"Lahore, Pakistan",31.5497,74.3436,22.3,23.7,33.1,13.6,1707.0,125.0,0.21,Moderate,2025-11-08 16:00:00,Moderado,8,11,2025,2025-11-08,16
17,2025-11-08 17:00:00,"Lahore, Pakistan",31.5497,74.3436,37.7,39.7,47.9,14.6,2408.0,97.0,0.24,Unhealthy for Sensitive,2025-11-08 17:00:00,Insalubre para grupos sensiveis,8,11,2025,2025-11-08,17
18,2025-11-08 18:00:00,"Lahore, Pakistan",31.5497,74.3436,50.1,52.0,61.6,15.4,3041.0,76.0,0.22,Unhealthy for Sensitive,2025-11-08 18:00:00,Insalubre para grupos sensiveis,8,11,2025,2025-11-08,18
19,2025-11-08 19:00:00,"Lahore, Pakistan",31.5497,74.3436,62.4,64.3,80.3,16.5,3665.0,47.0,0.21,Unhealthy,2025-11-08 19:00:00,Insalubre,8,11,2025,2025-11-08,19
20,2025-11-08 20:00:00,"Lahore, Pakistan",31.5497,74.3436,72.2,74.0,93.1,17.2,4128.0,26.0,0.21,Unhealthy,2025-11-08 20:00:00,Insalubre,8,11,2025,2025-11-08,20
21,2025-11-08 21:00:00,"Lahore, Pakistan",31.5497,74.3436,79.9,81.7,94.8,17.2,4431.0,18.0,0.20,Unhealthy,2025-11-08 21:00:00,Insalubre,8,11,2025,2025-11-08,21
22,2025-11-08 22:00:00,"Lahore, Pakistan",31.5497,74.3436,85.2,86.8,90.6,16.7,4573.0,18.0,0.20,Unhealthy,2025-11-08 22:00:00,Insalubre,8,11,2025,2025-11-08,22
23,2025-11-08 23:00:00,"Lahore, Pakistan",31.5497,74.3436,86.6,88.2,84.9,15.9,4404.0,20.0,0.19,Unhealthy,2025-11-08 23:00:00,Insalubre,8,11,2025,2025-11-08,23
24,2025-11-09 00:00:00,"Lahore, Pakistan",31.5497,74.3436,84.8,86.4,78.6,14.6,3698.0,24.0,0.17,Unhealthy,2025-11-09 00:00:00,Insalubre,9,11,2025,2025-11-09,0
25,2025-11-09 01:00:00,"Lahore, Pakistan",31.5497,74.3436,81.0,82.7,70.7,12.9,2680.0,29.0,0.16,Unhealthy,2025-11-09 01:00:00,Insalubre,9,11,2025,2025-11-09,1
26,2025-11-09 02:00:00,"Lahore, Pakistan",31.5497,74.3436,78.7,80.1,63.3,11.6,1883.0,34.0,0.15,Unhealthy,2025-11-09 02:00:00,Insalubre,9,11,2025,2025-11-09,2
27,2025-11-09 03:00:00,"Lahore, Pakistan",31.5497,74.3436,78.2,79.6,55.9,11.0,1481.0,36.0,0.15,Unhealthy,2025-11-09 03:00:00,Insalubre,9,11,2025,2025-11-09,3
28,2025-11-09 04:00:00,"Lahore, Pakistan",31.5497,74.3436,78.9,80.3,48.9,10.7,1300.0,37.0,0.14,Unhealthy,2025-11-09 04:00:00,Insalubre,9,11,2025,2025-11-09,4
29,2025-11-09 05:00:00,"Lahore, Pakistan",31.5497,74.3436,85.0,86.1,61.4,11.8,1342.0,25.0,0.17,Unhealthy,2025-11-09 05:00:00,Insalubre,9,11,2025,2025-11-09,5
30,2025-11-09 06:00:00,"Lahore, Pakistan",31.5497,74.3436,87.3,88.5,63.9,12.2,1805.0,22.0,0.16,Unhealthy,2025-11-09 06:00:00,Insalubre,9,11,2025,2025-11-09,6
31,2025-11-09 07:00:00,"Lahore, Pakistan",31.5497,74.3436,96.6,98.0,66.7,12.9,2491.0,21.0,0.15,Unhealthy,2025-11-09 07:00:00,Insalubre,9,11,2025,2025-11-09,7
32,2025-11-09 08:00:00,"Lahore, Pakistan",31.5497,74.3436,95.5,96.4,63.8,13.7,2815.0,31.0,0.15,Unhealthy,2025-11-09 08:00:00,Insalubre,9,11,2025,2025-11-09,8
33,2025-11-09 09:00:00,"Lahore, Pakistan",31.5497,74.3436,82.2,83.1,49.8,14.9,2410.0,65.0,0.14,Unhealthy,2025-11-09 09:00:00,Insalubre,9,11,2025,2025-11-09,9
34,2025-11-09 10:00:00,"Lahore, Pakistan",31.5497,74.3436,56.1,57.0,30.0,16.3,1642.0,112.0,0.15,Unhealthy,2025-11-09 10:00:00,Insalubre,9,11,2025,2025-11-09,10
35,2025-11-09 11:00:00,"Lahore, Pakistan",31.5497,74.3436,28.6,29.2,14.8,16.9,1022.0,147.0,0.15,Moderate,2025-11-09 11:00:00,Moderado,9,11,2025,2025-11-09,11
36,2025-11-09 12:00:00,"Lahore, Pakistan",31.5497,74.3436,20.0,20.3,7.1,16.0,677.0,163.0,0.16,Moderate,2025-11-09 12:00:00,Moderado,9,11,2025,2025-11-09,12
37,2025-11-09 13:00:00,"Lahore, Pakistan",31.5497,74.3436,17.6,18.0,4.0,14.3,481.0,168.0,0.17,Moderate,2025-11-09 13:00:00,Moderado,9,11,2025,2025-11-09,13
38,2025-11-09 14:00:00,"Lahore, Pakistan",31.5497,74.3436,16.8,17.3,6.8,13.0,563.0,164.0,0.17,Moderate,2025-11-09 14:00:00,Moderado,9,11,2025,2025-11-09,14
39,2025-11-09 15:00:00,"Lahore, Pakistan",31.5497,74.3436,16.8,17.2,18.0,12.5,1112.0,147.0,0.17,Moderate,2025-11-09 15:00:00,Moderado,9,11,2025,2025-11-09,15
40,2025-11-09 16:00:00,"Lahore, Pakistan",31.5497,74.3436,17.6,18.0,35.2,12.5,1939.0,121.0,0.17,Moderate,2025-11-09 16:00:00,Moderado,9,11,2025,2025-11-09,16
41,2025-11-09 17:00:00,"Lahore, Pakistan",31.5497,74.3436,36.1,36.7,55.6,12.6,2612.0,88.0,0.26,Unhealthy for Sensitive,2025-11-09 17:00:00,Insalubre para grupos sensiveis,9,11,2025,2025-11-09,17
42,2025-11-09 18:00:00,"Lahore, Pakistan",31.5497,74.3436,47.8,48.4,67.0,13.3,2946.0,70.0,0.25,Unhealthy for Sensitive,2025-11-09 18:00:00,Insalubre para grupos sensiveis,9,11,2025,2025-11-09,18
43,2025-11-09 19:00:00,"Lahore, Pakistan",31.5497,74.3436,58.7,59.3,82.7,14.3,3126.0,46.0,0.25,Unhealthy,2025-11-09 19:00:00,Insalubre,9,11,2025,2025-11-09,19
44,2025-11-09 20:00:00,"Lahore, Pakistan",31.5497,74.3436,67.3,68.0,94.0,15.1,3274.0,27.0,0.25,Unhealthy,2025-11-09 20:00:00,Insalubre,9,11,2025,2025-11-09,20
45,2025-11-09 21:00:00,"Lahore, Pakistan",31.5497,74.3436,75.0,75.7,97.2,15.5,3466.0,19.0,0.25,Unhealthy,2025-11-09 21:00:00,Insalubre,9,11,2025,2025-11-09,21
46,2025-11-09 22:00:00,"Lahore, Pakistan",31.5497,74.3436,82.2,82.9,96.1,15.7,3627.0,16.0,0.26,Unhealthy,2025-11-09 22:00:00,Insalubre,9,11,2025,2025-11-09,22
47,2025-11-09 23:00:00,"Lahore, Pakistan",31.5497,74.3436,87.3,88.0,92.6,15.6,3655.0,15.0,0.25,Unhealthy,2025-11-09 23:00:00,Insalubre,9,11,2025,2025-11-09,23
48,2025-11-10 00:00:00,"Lahore, Pakistan",31.5497,74.3436,89.6,90.6,86.8,15.0,3475.0,16.0,0.25,Unhealthy,2025-11-10 00:00:00,Insalubre,10,11,2025,2025-11-10,0
49,2025-11-10 01:00:00,"Lahore, Pakistan",31.5497,74.3436,90.8,91.7,78.6,14.0,3163.0,19.0,0.25,Unhealthy,2025-11-10 01:00:00,Insalubre,10,11,2025,2025-11-10,1